name: Build

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
      CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'yarn'
          registry-url: https://registry.npmjs.org/
      - run: yarn install --frozen-lockfile # optional, --immutable
      - run: yarn crowdin:sync
      - run: sleep 5 # wait for crowdin to sync
      - run: yarn crowdin:pull
      - run: yarn crowdin:copy
      - run: yarn build
      - run: tar -zcvf build.tar.gz ./build
      - run: tar -zcvf i18n.tar.gz ./i18n

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: |
            build.tar.gz
            i18n.tar.gz
